default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: book_dev

test:
  <<: *default
  database: book_tes

production:
  <<: *default
  database: book_production
